[theme]
primaryColor="#1DB954"
backgroundColor="#121212"
secondaryBackgroundColor="#212121"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
magicEnabled = false
